language: python
python:
    - "3.6"
before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"
    - sleep 3
    - "pip install pytest pytest-cov"
    - "pip install coveralls"
    - "pip install -U pip"
    - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
    - "python setup.py install"
bundler_args: --retry 5
script:
    - py.test
after_success:
    - coveralls
