language: python
xcode_project: AutoDiff
xcode_scheme: tests
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
script:
    - py.test
after_success:
    - coveralls
