language: python
xcode_project: AutoDiff
xcode_scheme: tests
virtualenv:
  system_site_packages: true
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
script:
    - py.test
after_success:
    - coveralls
