language: python
python:
    - "3.6"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
install:
  - export PYTHONPATH=$PYTHONPATH:$(pwd)/src/thermo
  - python3 setup.py install
script:
    - py.test
after_success:
    - coveralls
